
title: Bora Governar Junto!
email: boragovernarjunto@gmail.com
description: Movimento popular pela gestão participativa em Palmeiras (BA)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://boragovernarjunto.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

minima:
  date_format: "%e de %B de %Y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Github Pages mandatory config
lsi: false
safe: true
#source: https://github.com/BoraGovernarJunto/boragovernarjunto.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

